name: Test container image

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # We are running out of space while building the image, because it is quite big
    # https://github.com/actions/virtual-environments/issues/2606#issuecomment-772683150
    # and https://github.com/easimon/maximize-build-space/blob/b4d02c14493a9653fe7af06cc89ca5298071c66e/action.yml#L104
    # This gains us an additional 33GB, to go with initial 14GB
    - name: cleanup disk space
      run: |
        sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
        df -h

    - name: checkout files in repo
      uses: actions/checkout@main

    - name: Build and push the image
      uses: yuvipanda/repo2docker-action@docker-push
      with:
        DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        DOCKER_REGISTRY: "quay.io"
        IMAGE_NAME: "2i2c/utoronto-image"
        ADDITIONAL_TAG: "test"

    - name: Report disk space
      run: df -h